import Link from "next/link"  
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
          <div className="navbar">
            <Link href="/">홈</Link>
            <Link href="/list">list</Link>
            <Link href="/cart">cart</Link>
          </div>
          <div className="sidebar">
            <Link href="/sb1">학사일정</Link>
            <Link href="/sb2">내 강의실</Link>
            <Link href="/sb3">우리반</Link>
            <Link href="/sb4">sidebar4</Link>
            <Link href="/sb5">sidebar5</Link>

          </div>
          <div className="contents">
          
            {children}

          </div>
      </body>
    </html>
  );
}

